### PR TITLE
Add /ping public entrypoint

### PR DESCRIPTION
**Pull request by tangrammer**
```
 curl -i 'http://localhost:8888/ping'
HTTP/1.1 200 OK
Content-Type: text/plain;charset=utf-8
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Server: Development/1.0
Date: Thu, 06 Aug 2020 17:53:55 GMT
Content-Length: 5

ping
```

#### Reviewer Checklist
* [ ] Added an explanation about the work done
* [ ] Connected the PR and the issue on Zenhub
* [ ] Added a test plan to the issue
* [ ] Updated the copyright header (when relevant)
* [ ] Formatted the code
* [ ] Added a documentation (if relevant)
* [ ] Added some unit tests (if relevant)

### CODE REVIEW

**Comment by tangrammer** [comment]
@marvinkome added http://localhost:8888/ping :) see [description](https://github.com/akvo/akvo-flow/pull/3625#issue-464180013)

**Comment by iperdomo** [comment]
I think if we want to check internet connectivity is _better™_ to rely on something like https://www.google.com/generate_204

**Comment by tangrammer** [comment]
@iperdomo 
looking my network request i see `cache-control: max-age=0`
Screenshot 2020-10-07 at 09 22 23

not sure about the cache "thing" 🤔 https://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache

**Comment by iperdomo** [comment]
The `Cache-Control: max-age=0` means that this HTTP response **must not** be cached. The browser **must** request it again every time.

**Comment by iperdomo** [comment]
Closing the PR. We can re-open it when we focus again in this issue

**Pull request closed without merging**
