### PR TITLE
[#1082] Code improvements on RemoteAPI class

### PR DESCRIPTION
**Pull request by iperdomo**
* The Process now has a DataStoreService parameter, that avoids making
  that call on each implemetation

### CODE REVIEW

**Comment by iperdomo** [comment]
## Checklist

* [ ] Test plan
* [ ] Copyright header
* [ ] Code formatting

**Comment by muloem** [comment]
I just made a small test for a survey I had to delete and got an NPE on this line https://github.com/akvo/akvo-flow/pull/1084/files#diff-b19a6baca0372cab8836a9ba612f22d8R73

**Comment by iperdomo** [comment]
@muloem that means _old data_ has not be updated. I'll make a null check there.

**Comment by muloem** [comment]
True. I noticed that afterwards. The rest is good to go. I will merge.

**Comment by muloem** [comment]
:+1: code reviewed!

**Pull request merged**
