### PR TITLE
[#1203] remove '_copy' when copying a questionId

### PR DESCRIPTION
**Pull request by mtwestra**

### CODE REVIEW

**Comment by iperdomo** [comment]
## Checklist

* [ ] Test plan
* [ ] Copyright header
* [ ] Code formatting

**Comment by muloem** [comment]
As @jonase mentioned, this function is also used for copying questions *within* a survey and in these cases the question ID needs to be unique. e.g copying question groups.

**Comment by mtwestra** [comment]
@muloem I see what you mean. So we will need to know when we are copying within a survey, and when not. Depending on that, the behaviour could change?

**Comment by muloem** [comment]
@mtwestra yes. exactly.

**Comment by jonase** [comment]
Here's another scenario that is currently problematic:

1. Create a question with question identifier `foo``
2. Copy the question, the new identifier will be `foo_copy` (so far so good)
3. Copy the same question one more time, this question will get the same identifier as the previous copy.

**Comment by muloem** [comment]
Implementation needs some rework based on comments.

**Pull request closed without merging**
