### PR TITLE
[#3576] Add Question.personalData boolean attribute [backend]

### PR DESCRIPTION
**Pull request by tangrammer**
Relates #3576 
#### Screenshots (if appropriate)
Screenshot 2020-05-28 at 15 52 26

#### Reviewer Checklist
* [ ] Added an explanation about the work done
* [ ] Connected the PR and the issue on Zenhub
* [ ] Added a test plan to the issue
* [ ] Updated the copyright header (when relevant)
* [ ] Formatted the code
* [ ] Added a documentation (if relevant)
* [ ] Added some unit tests (if relevant)

### CODE REVIEW

**Comment by tangrammer** [comment]
@muloem how could I test the xml report generation?

**Comment by muloem** [comment]
@tangrammer you have some unit tests. that would be the first easy place to start.

**Comment by muloem** [comment]
note that in #3585 the property is `holdPersonalData` so either you or @marvinkome have to change the property name otherwise it needs special code to translate from one to the other.

**Comment by marvinkome** [comment]
I've changed the field to `personalData` on the client side

**Comment by tangrammer** [comment]
> I guess we can also update the XML generation tests `org.akvo.flow.xml.FlowXmlObjectWriterTests`

added https://github.com/akvo/akvo-flow/pull/3587/commits/4b801e47a57ed4a74a679957c7d632ab5c075990

**Pull request merged**
