### PR TITLE
[#2651] Cache local_db.bin under GAE/tmp folder (connect #2651)

### PR DESCRIPTION
**Pull request by iperdomo**
- This avoids the need of downloading a 45MB file every time we
  clean the GAE/target folder

## Checklist
* [x] Connect the issue
* [ ] Test plan
* [x] Copyright header
* [ ] Code formatting
* [ ] Documentation

### CODE REVIEW

**Comment by dlebrero** [comment]
The problem with this approach is that you lose the data if you do a "mvn clean ...". I know @stellanl has complain about this before.

Could you please have a look at https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/190 to see if it possible to use a different path, outside the  target directory to store **both** the db and the generated files? Or check with the Flow team what is the desired behaviour?

**Comment by iperdomo** [comment]
@dlebrero i saw @muloem doing `rm -rf GAE/target` directly to start clean, so no `mvn` involved.
The main idea is to stop downloading the `local_db.bin`, specially problematic to some team members on slow/expensive internet links.

**Comment by iperdomo** [comment]
I found a couple of interesting properties:

* `devserver.clearDatastore` - Clear the application's local datastore at startup.
* `devserver.storagePath` - Path to the data (datastore, blobstore, etc.) associated with the application.

https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference

**Comment by iperdomo** [comment]
I've been trying to use the mentioned properties `devserver.clearDatastore` and `devserver.storagePath` but for that we need to opt-in and use `2-alpha` version of the _DevServer_

When running the version `2-alpha` we have a really complex set of process/child-process relationship that I have not been able to get it to work. e.g.
````
bash-4.4$ ps faxww
  PID TTY      STAT   TIME COMMAND
  203 pts/0    Ss     0:00 bash
  210 pts/0    R+     0:00  \_ ps faxww
    1 ?        Ss     0:00 bash /app/src/ci/devserver.sh
   15 ?        Sl     0:00 /usr/local/bundle/bin/rake watchbg
   50 ?        Sl     0:05  \_ /usr/local/bundle/bin/guard start --no-interactions
   16 ?        Sl     0:28 /usr/bin/java -Xmx512m -classpath /usr/share/java/maven-3/boot/plexus-classworlds-2.5.2.jar -Dclassworlds.conf=/usr/share/java/maven-3/bin/m2.conf -Dmaven.home=/usr/share/java/maven-3 -Dlibrary.jansi.path=/usr/share/java/maven-3/lib/jansi-native -Dmaven.multiModuleProjectDirectory=/app/src/GAE org.codehaus.plexus.classworlds.launcher.Launcher appengine:run
   88 ?        S      0:00  \_ python /google-cloud-sdk/bin/dev_appserver.py /app/src/GAE/target/akvo-flow --host=0.0.0.0 --port=8888 --storage_path=/app/src/GAE/data --jvm_flag=-Xdebug --jvm_flag=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 --runtime=java --dev_appserver_log_level=debug --clear_datastore=false
   93 ?        Sl     0:06      \_ /usr/bin/python /google-cloud-sdk/platform/google_appengine/dev_appserver.py --skip_sdk_update_check=True /app/src/GAE/target/akvo-flow --host=0.0.0.0 --port=8888 --storage_path=/app/src/GAE/data --jvm_flag=-Xdebug --jvm_flag=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 --runtime=java --dev_appserver_log_level=debug --clear_datastore=false
  100 ?        Sl     0:13          \_ /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -cp /google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar -Dappengine.sdk.root=/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java -Dappengine.runtime=java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 com.google.appengine.tools.development.devappserver2.StandaloneInstance /tmp/tmpERlu1w /tmp/tmp8Mum0
````
I propose to revisit the new version of the `DevServer` after we move to java 8 as runtime

**Pull request merged**
