### PR TITLE
[#3416] - use uglify plugin to remove comments from prod bundle

### PR DESCRIPTION
**Pull request by marvinkome**
#### Before the PR (what is the issue or what needed to be done)
Lots of redundant comments were in the dashboard bundle file

#### The solution
Use the `uglify` plugin to remove these redundant comments

#### Reviewer Checklist
* [ ] Added an explanation about the work done
* [ ] Connected the PR and the issue on Zenhub
* [ ] Added a test plan to the issue
* [ ] Updated the copyright header (when relevant)
* [ ] Formatted the code
* [ ] Added a documentation (if relevant)
* [ ] Added some unit tests (if relevant)

### CODE REVIEW

**Comment by muloem** [comment]
I  just noticed this.  but one question... wasnt the uglifier already enabled?  Whats the added value of the extra package?

https://github.com/akvo/akvo-flow/blob/3339cf004fc58436bca17f31f88696aaf20076c3/Dashboard/webpack.config.prod.js#L11-L15

**Comment by marvinkome** [comment]
That's for the HTML

**Comment by muloem** [comment]
It also seems to configure the rest.... including CSS and JS...

https://github.com/akvo/akvo-flow/blob/3339cf004fc58436bca17f31f88696aaf20076c3/Dashboard/webpack.config.prod.js#L11-L26

**Comment by marvinkome** [comment]
https://github.com/jantimon/html-webpack-plugin#minification This is what I found in the documentation

**Pull request merged**
