### PR TITLE
[#1204] Raw data report additions

### PR DESCRIPTION
**Pull request by jonase**
* Add identifier and display name columns to non-monitoring data exports
* Add device identifier column to data exports

### CODE REVIEW

**Comment by iperdomo** [comment]
## Checklist

* [ ] Test plan
* [ ] Copyright header
* [ ] Code formatting

**Comment by muloem** [comment]
@jonase will this affect the import as well?  i.e. do we expect these two columns not to be there when importing non-monitoring surveys?

**Comment by jonase** [comment]
@muloem It seems that this breaks data cleaning, yes. I'll try to fix this today.

**Comment by muloem** [comment]
:+1: code reviewed!

**Pull request merged**
