### PR TITLE
Issue/2466 gdpr steps (connect #2466)

### PR DESCRIPTION
**Pull request by loicsans**

### CODE REVIEW

**Comment by loicsans** [comment]
I've updated the bulk data upload screen to match the design decisions made. @janagombitova do you ave the final copy at hand so I can finish this?

screen shot 2018-02-23 at 14 27 02

**Comment by janagombitova** [comment]
@loicsans Here you go: 

https://user-images.githubusercontent.com/12456965/35720121-aef8a0de-07ec-11e8-8036-9a11af290dde.png

- The walk through should have a title: **How to prepare and upload data collected offline** 
- Image 1: Title: **Locate the data** 
- Image 1: copy: Use the Publish data option in the Flow app Settings to locate the data once you connect the device to your PC. 
- Image 2: Title: **Copy the data and zip it** 
- Image 2: copy: Copy the data to your PC and compress it to a .zip file.
- Image 3: Title: **Upload the zip file** 
- Image 3: copy: Upload the zip file as instructed below.

The text outside the images should be implemented in such a way that we can get all the text translated. 

Secondly, in Kiarri's designs the walkthrough should be "close-able". The user can decide not to see it again, and then it should not show at all the next time he logs into Flow and comes to this page. Or he can choose to close the window.

**Comment by muloem** [comment]
This will go into the next release alongside the changes in the app. 👍

**Comment by janagombitova** [comment]
@muloem and @loicsans is it possible for me to review this sooner? On another instance for example - https://uat2.akvoflow.org/? It is quite something new for Flow and I want to make sure it works well and we did not forget anything in the implementation.

**Comment by muloem** [comment]
Absolutely!

**Comment by loicsans** [comment]
screen shot 2018-04-12 at 19 17 02
The file uploaded list has been added to the dropping area.

**Comment by janagombitova** [comment]
@loicsans I have one question. The last step we repeat Upload the zip file in the title and in the text. I just noticed that. Should we change the text or remove it? What do you think?

**Comment by kymni** [comment]
Closing this as it'll be tackled on #2587

**Pull request closed without merging**
