### PR TITLE
[#1972] table header in messages tab gest fixed while scrolling (connect #1972)

### PR DESCRIPTION
**Pull request by loicsans**

### CODE REVIEW

**Comment by loicsans** [comment]
It behaves like this: 
apr-06-2017 14-13-10

**Comment by loicsans** [comment]
The cells are now displaying the content properly.
apr-06-2017 15-55-32

**Comment by janagombitova** [comment]
@loicsans would it be possible to make the Date and Form ID columns a bit narrower to create more space for the Survey column, as this one can hold quite a long string of texts?

**Comment by loicsans** [comment]
apr-26-2017 14-48-05

**Pull request merged**
