### PR TITLE
[#1975] Fixed the form name being cut inside the tab (connect #1975) 

### PR DESCRIPTION
**Pull request by loicsans**

### CODE REVIEW

**Comment by loicsans** [comment]
screen shot 2017-03-21 at 18 01 11
Long form titles are now displayed with an ellipsis inside tabs which are constraint to a max width.

**Comment by loicsans** [comment]
Taking this further: the add form button, in case of monitoring unabled is moved aligned to the tabs themselves on the right for a more intuitive location. Also removed the "Forms:" header.
screen shot 2017-03-21 at 18 34 14

**Comment by loicsans** [comment]
The last commit should look like this: 
screen shot 2017-04-05 at 14 44 43

**Comment by janagombitova** [comment]
@muloem just a note in case you started review already, @loicsans will also remove the white tab from the screen

screen shot 2017-04-05 at 15 16 10

**Comment by loicsans** [comment]
it doesn't for me
screen shot 2017-04-06 at 7 19 53

**Comment by loicsans** [comment]
@muloem I cannot reproduce the gap you see between the tabs and the content. Caching issue again?

**Comment by janagombitova** [comment]
Hi @loicsans and @muloem, could the gap be because you have the page zoomed out? I had it last time with a different part of Flow that when i was looking at the page in 100% everything was fine, but when going to 90% things were out of position.

**Comment by muloem** [comment]
@loicsans @janagombitova I am deploying this branch to beta1 to confirm.  On my env its neither cached nor at a special zoom.

**Comment by janagombitova** [comment]
@mulo and @loicsans I cross checked on beta1 on Safari and Chrome and all appears well. The button does not float over and there is not space under the tabs. Appears good to me 👍

**Pull request merged**
